version: '3.5'
services:
  milvus-standalone:
    image: milvusdb/milvus:v2.6.0
    container_name: milvus-standalone
    ports:
      - "19530:19530"
      - "9091:9091"
    volumes:
      - ./volumes/milvus/db:/var/lib/milvus/db
      - ./volumes/milvus/conf:/etc/milvus
    restart: always
